spring:
  application:
    name: FrontEnd
server.port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
auth:
  user: admin
  password: '{bcrypt}$2a$10$4FtlQ0Ex4VeneIOztJ1lT.Oor2Pqk6xzgXdb2APcbZqbBAV1eh6aO'