spring:
  application:
    name: Storage
  rabbitmq:
    username: info
    password: news
    host: rabbitmq-server
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2

  cache:
    jcache:
      config: classpath:ehcache.xml
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://mongodb:27017/test
server.port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry_area:8761/eureka/
    instance:
      preferIpAddress: true